language: python

# Python versions to test
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

# Install dependencies
install:
  - pip install --upgrade pip
  - pip install -e ".[dev]"

# Run tests
script:
  - pytest tests/ -v --cov=MergeSourceFile --cov-report=term-missing

# Additional configuration
cache:
  pip: true

# Notifications (optional, can be configured later)
notifications:
  email: false
