version: 2.1

# Define workflows
workflows:
  test-workflow:
    jobs:
      - test-python-311
      - test-python-312
      - test-python-313

# Define jobs
jobs:
  test-python-311: &test-template
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Update pip and install build tools
          command: |
            python -m pip install --upgrade pip setuptools>=75.0.0 wheel build
      - run:
          name: Install project dependencies
          command: |
            pip install -e ".[dev]"
      - run:
          name: Run tests with coverage
          command: |
            python -m pytest tests/ -v --cov=MergeSourceFile --cov-report=xml --cov-report=term-missing
      - run:
          name: Upload coverage to Codecov
          command: |
            pip install codecov
            codecov
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml

  test-python-312:
    <<: *test-template
    docker:
      - image: cimg/python:3.12

  test-python-313:
    <<: *test-template
    docker:
      - image: cimg/python:3.13