version: 2.1

# Define workflows
workflows:
  test-workflow:
    jobs:
      - test-python-38
      - test-python-39
      - test-python-310
      - test-python-311
      - test-python-312

# Define jobs
jobs:
  test-python-38: &test-template
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Update pip and install build tools
          command: |
            python -m pip install --upgrade pip setuptools>=77.0.0 wheel build
      - run:
          name: Install project dependencies
          command: |
            pip install -e ".[dev]"
      - run:
          name: Run tests with coverage
          command: |
            python -m pytest tests/ -v --cov=MergeSourceFile --cov-report=xml --cov-report=term-missing
      - run:
          name: Upload coverage to Codecov
          command: |
            pip install codecov
            codecov
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage.xml

  test-python-39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9

  test-python-310:
    <<: *test-template
    docker:
      - image: cimg/python:3.10

  test-python-311:
    <<: *test-template
    docker:
      - image: cimg/python:3.11

  test-python-312:
    <<: *test-template
    docker:
      - image: cimg/python:3.12